guard 'rspec', cmd: 'bundle exec rspec' do
  # watch /lib/ files
  watch(%r{^lib/(.+).rb$}) do |m|
    p "spec/#{m[1]}_spec.rb"
    "spec/#{m[1]}_spec.rb"
  end

  #watch /spec/files
  watch(%r{^spec/(.+).rb$}) do |m|
    p "spec/#{m[1]}.rb"
    "spec/#{m[1]}.rb"
  end

  watch('spec/spec_helper.rb')  { "spec" }
end
