---
driver:
  name: docker
  binary: docker.io

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  # - name: ubuntu-14.04
  # - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
  # - name: ssl
  #   runlist:
  #     - recipe[apache::ssl]
